name: joinme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  intl: ^0.19.0
  geolocator: ^9.0.2
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  firebase_storage: ^12.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png